server:
  port: 8085

spring:
  application:
    name: game-service
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: k10a508.p.ssafy.io
      port: 6379

#k10a508.p.ssafy.io
  profiles:
    include:
      - cors
      - secret

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k10a508.p.ssafy.io:8083/eureka
#      http://localhost:8761/eureka
#      http://k10a508.p.ssafy.io:8083/eureka

  instance:
    hostname: 43.202.53.115