spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    time-zone: Asia/Seoul
  application:
    name: study-service
  profiles:
    include:
      - secret
  kafka:
    consumer:
      bootstrap-servers: k10a508.p.ssafy.io:9092 # 카프카 브로커 주소
      group-id: study-group
      auto-offset-reset: earliest # 가장 오래된 레코드부터 읽기 시작
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages:  "*"
        spring.json.value.default.type: com.a508.studyservice.kafka.NotificationMessage

app:
  kafka:
    topic: user-events

server:
  port: 8086
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k10a508.p.ssafy.io:8083/eureka
  instance:
    hostname: 43.202.53.115
logging:
  level:
    org.springframework.web.servlet.resource: ERROR