server:
  port: 8087

spring:
  application:
    name: mypage-service

  profiles:
    include:
      - secret


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8083/eureka
#      http://localhost:8083/eureka
