server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k10a508.p.ssafy.io:8083/eureka
#      http://localhost:8083/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/**
